---
- name: Install nginx
  yum: name=nginx state=present

- name: Copy nginx configuration for Application Loadbalancing
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
