---
# Copy And Load DB 


- name:  create database
  mysql_db: name={{ db_name }} state=present

- name: Create Wordpress database user
  mysql_user: name={{ db_user }} password={{ db_password }} priv={{ db_name }}.*:ALL host='localhost' state=present

- copy: src=test.sql dest=/tmp

- name: Populate Database 
  mysql_db: name={{ db_name }} state=import  target=/tmp/test.sql 

- name: Copy Wordpress config file
  copy: src=test.php dest=/var/www/html/index.php

